---
- name: Install Nginx
  apt: name=nginx update_cache=yes state=latest

- name: install letsencrypt
  apt: name=letsencrypt state=latest

- name: create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

# This needs to be upgraded to allow the port to be open before using nginx
# UFW Configuration
- name: "UFW - Allow HTTP on port {{ https_port }}"
  ufw:
    rule: allow
    port: "{{ https_port }}"
    proto: tcp

#- name: Remove default nginx config
#  file: name=/etc/nginx/sites-enabled/default state=absent

#- name: Install system nginx config
#  template:
#    src: templates/nginx.conf.j2
#    dest: /etc/nginx/nginx.conf

# Nginx Configuration
- name: Sets Nginx conf file
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ http_host }}"

#- name: Creates nginx ssl options
#  template:
#    src: "options-ssl-nginx.conf.j2"
#    dest: "/etc/letsencrypt/options-ssl-nginx.conf"

- name: Enables new site
  file:
    src: "/etc/nginx/sites-available/{{ http_host }}"
    dest: "/etc/nginx/sites-enabled/{{ http_host }}"
    state: link
  notify: Reload Nginx

- name: Removes "default" site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx

# This needs to be removed to let the certificate be created
#- name: Reload nginx to activate letsencrypt site
#  service: name=nginx state=restarted

# Need to stop the nginx service to allow for the certificate to be generated
#- name: Reload nginx to activate letsencrypt site
#  service: name=nginx state=stopped
#
#- name: Create letsencrypt certificate
#  shell: letsencrypt certonly -n --webroot -w /var/www/packetpigeon -m {{ letsencrypt_email }} --agree-tos -d {{ http_host }}
#  args:
#    creates: /etc/letsencrypt/live/{{ http_host }}

#- name: Generate dhparams
#  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
#  args:
#    creates: /etc/nginx/dhparams.pem

#- name: Add letsencrypt cronjob for cert renewal
#  cron:
#    name: letsencrypt_renewal
#    special_time: weekly
#    job: letsencrypt --renew certonly -n --webroot -w /var/www/packetpigeon -m {{ letsencrypt_email }} --agree-tos -d {{ http_host }}
#  notify: Reload Nginx

# This needs to be removed to allow the certificate to be renewed
- name: Reload nginx to activate specified site
  service: name=nginx state=restarted
