---
- hosts: all
  become: true
  roles:
    - { role: setup, tags: ['setup'] }

#    - { role: mariadb, tags: ['mysql', 'mariadb', 'db', 'lemp'] }

    - { role: php, tags: ['php', 'web', 'php-fpm', 'lemp'] }

    - { role: composer, tags: ['composer'] }
