---
php_packages: [ "php7.2", "php7.2-mysql", "php7.2-soap", "php7.2-bcmath", "php7.2-xml", "php7.2-mbstring", "php7.2-gd", "php7.2-common", "php7.2-cli", "php7.2-curl", "php7.2-intl", "php7.2-zip", "zip", "unzip" ]
php_file_uploads: "On"
php_upload_max_filesize: "64M"
php_max_file_uploads: "20"
php_post_max_size: "32M"
